name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws/dev

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format
        run: terraform fmt -check -no-color

      # No backend, no provider auth needed
      - name: Terraform Init (no backend)
        run: terraform init -input=false -no-color

      - name: Terraform Validate
        run: terraform validate -no-color

      # Intentionally skip plan because data sources need AWS creds
      # - name: Terraform Plan
      #   run: terraform plan -no-color
