name: Terraform
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  tf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # add later: id-token: write  # for OIDC

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check
      - run: terraform validate

      # Enable later once OIDC + backend exist
      - name: Terraform Init (S3 backend)
        if: false   # change to true after backend/creds
        run: terraform init -input=false -no-color

      - name: Terraform Plan (PRs)
        if: false   # enable later (or guard on event == pull_request)
        run: terraform plan -input=false -no-color

      - name: Terraform Apply (main only, gated)
        if: false   # enable later; you can also use environments/approvals
        run: terraform apply -auto-approve -input=false -no-color
