jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check

      # 👇 downloads providers/modules without touching your S3 backend
      - name: Terraform Init (no backend)
        run: terraform init -backend=false -upgrade -input=false -no-color

      - name: Terraform Validate
        run: terraform validate -no-color