name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check

      # download providers without touching the backend (OK until S3 backend is ready)
      - name: Terraform Init (no backend)
        run: terraform init -backend=false -upgrade -input=false -no-color

      - name: Terraform Validate
        run: terraform validate -no-color
